// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PRN212_Project_StudentManagement.Models;

#nullable disable

namespace PRN212_Project_StudentManagement.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20250727080433_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Vietnamese_CI_AS")
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PRN212_Project_StudentManagement.Models.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ClassID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<int>("AcademicFromYear")
                        .HasColumnType("int");

                    b.Property<int>("AcademicToYear")
                        .HasColumnType("int");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("TeacherID");

                    b.HasKey("ClassId")
                        .HasName("PK__Classes__CB1927A09D1D3B38");

                    b.HasIndex("TeacherId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("PRN212_Project_StudentManagement.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DepartmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DepartmentId")
                        .HasName("PK__Departme__B2079BCDEEC695D9");

                    b.HasIndex(new[] { "DepartmentName" }, "UQ__Departme__D949CC34B9B1CEDB")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("PRN212_Project_StudentManagement.Models.Manager", b =>
                {
                    b.Property<int>("ManagerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ManagerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManagerId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("DepartmentID");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ManagerId")
                        .HasName("PK__Managers__3BA2AA8116532A31");

                    b.HasIndex("DepartmentId");

                    b.HasIndex(new[] { "UserId" }, "UQ__Managers__1788CCAD81D5B89E")
                        .IsUnique();

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("PRN212_Project_StudentManagement.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("ClassID");

                    b.Property<DateOnly>("EnrollmentDate")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("StudentId")
                        .HasName("PK__Students__32C52A794EBE9875");

                    b.HasIndex("ClassId");

                    b.HasIndex(new[] { "UserId" }, "UQ__Students__1788CCAD8F4E9C1C")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("PRN212_Project_StudentManagement.Models.StudentLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ActionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ChangeById")
                        .HasColumnType("int")
                        .HasColumnName("ChangeByID");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NewData")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OldData")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.HasKey("LogId")
                        .HasName("PK__StudentL__5E5499A8E07ABA01");

                    b.HasIndex("ChangeById");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentLogs");
                });

            modelBuilder.Entity("PRN212_Project_StudentManagement.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SubjectID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SubjectId")
                        .HasName("PK__Subjects__AC1BA388ABEC70C5");

                    b.HasIndex(new[] { "SubjectName" }, "UQ__Subjects__4C5A7D55F34FA3C3")
                        .IsUnique();

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("PRN212_Project_StudentManagement.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TeacherID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherId"));

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("SubjectID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("TeacherId")
                        .HasName("PK__Teachers__EDF259449B02CAA0");

                    b.HasIndex("SubjectId");

                    b.HasIndex(new[] { "UserId" }, "UQ__Teachers__1788CCADE4DA389A")
                        .IsUnique();

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("PRN212_Project_StudentManagement.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CCACE458F1CA");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D105344AD61B23")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PRN212_Project_StudentManagement.Models.Class", b =>
                {
                    b.HasOne("PRN212_Project_StudentManagement.Models.Teacher", "Teacher")
                        .WithMany("Classes")
                        .HasForeignKey("TeacherId")
                        .HasConstraintName("FK__Classes__Teacher__4BAC3F29");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("PRN212_Project_StudentManagement.Models.Manager", b =>
                {
                    b.HasOne("PRN212_Project_StudentManagement.Models.Department", "Department")
                        .WithMany("Managers")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK__Managers__Depart__440B1D61");

                    b.HasOne("PRN212_Project_StudentManagement.Models.User", "User")
                        .WithOne("Manager")
                        .HasForeignKey("PRN212_Project_StudentManagement.Models.Manager", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Managers__UserID__4316F928");

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRN212_Project_StudentManagement.Models.Student", b =>
                {
                    b.HasOne("PRN212_Project_StudentManagement.Models.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK__Students__ClassI__5070F446");

                    b.HasOne("PRN212_Project_StudentManagement.Models.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("PRN212_Project_StudentManagement.Models.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Students__UserID__4F7CD00D");

                    b.Navigation("Class");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRN212_Project_StudentManagement.Models.StudentLog", b =>
                {
                    b.HasOne("PRN212_Project_StudentManagement.Models.User", "ChangeBy")
                        .WithMany("StudentLogs")
                        .HasForeignKey("ChangeById")
                        .IsRequired()
                        .HasConstraintName("FK__StudentLo__Chang__5535A963");

                    b.HasOne("PRN212_Project_StudentManagement.Models.Student", "Student")
                        .WithMany("StudentLogs")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__StudentLo__Stude__5441852A");

                    b.Navigation("ChangeBy");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PRN212_Project_StudentManagement.Models.Teacher", b =>
                {
                    b.HasOne("PRN212_Project_StudentManagement.Models.Subject", "Subject")
                        .WithMany("Teachers")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK__Teachers__Subjec__48CFD27E");

                    b.HasOne("PRN212_Project_StudentManagement.Models.User", "User")
                        .WithOne("Teacher")
                        .HasForeignKey("PRN212_Project_StudentManagement.Models.Teacher", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Teachers__UserID__47DBAE45");

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PRN212_Project_StudentManagement.Models.Class", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("PRN212_Project_StudentManagement.Models.Department", b =>
                {
                    b.Navigation("Managers");
                });

            modelBuilder.Entity("PRN212_Project_StudentManagement.Models.Student", b =>
                {
                    b.Navigation("StudentLogs");
                });

            modelBuilder.Entity("PRN212_Project_StudentManagement.Models.Subject", b =>
                {
                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("PRN212_Project_StudentManagement.Models.Teacher", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("PRN212_Project_StudentManagement.Models.User", b =>
                {
                    b.Navigation("Manager");

                    b.Navigation("Student");

                    b.Navigation("StudentLogs");

                    b.Navigation("Teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
